/*!
 * eMdException 
 * 
 * Parent Object for Exception generated by eMd
 * 
 * 
 * Copyright(c) 20017 Jean-Luc Ranaivoarivao <ranaivoarivaojl@me.com>
 * MIT Licensed
 */

function eMdException( message ){
  this.message = message;
}

eMdException.prototype = {

}

module.exports = eMdException;