/*!
 * eMdException 
 * 
 * Parent Object for Exception generated by eMd
 * 
 * 
 * Copyright(c) 20017 Jean-Luc Ranaivoarivao <ranaivoarivaojl@me.com>
 * MIT Licensed
 */

var severities = [ "fatal", "warning", "notice", "deprecated" ];

function eMdException( message, severity ){
  this.message = message;
  this.severity = undefined;
}

eMdException.prototype = {
  
  /**
   * setSeverity()
   * set the exception severity
   * fatal, warning, notice, deprecated
   * 
   * @return {Array} md Returns found (in constructor) eMd strings inside an array
   */
  setSeverity : function( severity ){
    if( severities.indexOf(severity) !== -1 ){
      this.severity = severity;
    }else{
      throw "Unknow severity "+severity;
    }
  }
}

module.exports = eMdException;