/*!
 * EMdException
 *
 * Parent Object for Exception generated by eMd
 *
 * @TODO Add OperationNumber, Line and Column informations to exception
 *
 * Copyright(c) 20017 Jean-Luc Ranaivoarivao <ranaivoarivaojl@me.com>
 * MIT Licensed
 */

class EMdException {

  constructor(message, severity) {
    this.message = message;
    this.severity = undefined;
    this.severities = ["fatal", "warning", "notice", "deprecated"];
  }

  /**
   * setSeverity()
   * set the exception severity
   * fatal, warning, notice, deprecated
   *
   * @return {Array} md Returns found (in constructor) eMd strings inside an array
   */
  setSeverity(severity) {
    if (this.severities.indexOf(severity) !== -1) {
      this.severity = severity;
    } else {
      throw "Unknow severity " + severity;
    }
  }

  toJSON() {
    return {
      message: this.message,
      severity:  this.severity
    };
  }
}

module.exports = EMdException;
